name: e2e

on:
  pull_request:
    branches:
      - master
      - 'release-*'
    paths-ignore:
      - 'apiserver/**'
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - 'LICENSE'
  push:
    branches:
      - master
      - 'release-*'
    paths-ignore:
      - 'apiserver/**'
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - 'LICENSE'

concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  ray-operator:
    uses: ./.github/workflows/e2e-tests-reusable-workflow.yaml
    with:
      plugin-test: false
      dir-to-test: ray-operator

  ray-kubectl-plugin:
    uses: ./.github/workflows/e2e-tests-reusable-workflow.yaml
    with:
      plugin-test: true
      dir-to-test: kubectl-plugin
